In [1]:
import numpy as np

## 1. The ndarray — NumPy's Core Object

##Concept: A Python list stores objects with overhead per item.
A NumPy ndarray stores raw values of one fixed type in a contiguous memory block
— like a spreadsheet row vs. a folder of loose sticky notes.
This is why NumPy is fast: operations run in optimized C loops, not Python loops.

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])   # 2D array (matrix)

print(a.ndim)    # number of dimensions
print(b.shape)   # rows, columns
print(a.dtype)   # data type of elements
print(a.size)    # total number of elements

1
(2, 2)
int64
3


# Assignment
Exercises 1
Create a 1D array of the numbers 10 to 50.

Create a 3x3 array of zeros, then check its .shape and .dtype.

Create a 2D array from [[1,2,3],[4,5,6]] and print its .ndim, .shape, .size.

In [6]:
# 1
a = np.array(range(10, 51))

# 2
z = np.zeros((3, 3))
print(z.shape, z.dtype)

# 3
m = np.array([[1,2,3],[4,5,6]])
print(m.ndim)
print(m.shape)
print(m.size)

(3, 3) float64
2
(2, 3)
6


**Creating Arrays**

 Concept: You rarely type out arrays by hand, you generate them with builder functions.

In [8]:
#codes from previous class
np.zeros((2, 3))          # array of zeros, shape (2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3))           # array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((2, 2), 7)        # array filled with 7

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(3)                 # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(0, 10, 2)       # [0 2 4 6 8]  (like range())

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0, 1, 5)      # 5 evenly spaced values from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.rand(2, 2)      # random floats in [0,1)

array([[0.88373977, 0.47907192],
       [0.47642009, 0.29644731]])

In [15]:
np.random.randint(0, 10, size=(2,2))  # random ints

array([[4, 2],
       [1, 7]])

**Assignment 2**

Create a 4x4 identity matrix.

Create an array of 10 evenly spaced numbers between 0 and 100.

Create a 3x3 array of random integers between 1 and 6 (simulate dice rolls).

In [16]:
# 1
np.eye(4)

# 2
np.linspace(0, 100, 10)

# 3
np.random.randint(1, 7, size=(3, 3))

array([[4, 2, 6],
       [5, 3, 3],
       [3, 2, 6]])

**Indexing and Slicing**

Concept: Like Python lists, but extended to multiple dimensions using comma-separated indices: array[row, column].

In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[0, 0]      # single element


np.int64(1)

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[1, :]      # entire row


array([4, 5, 6])

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[:, 1]      #  entire column

array([2, 5, 8])

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0:2, 0:2]  # top-left 2x2 block

array([[1, 2],
       [4, 5]])

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[a > 5]     #  [6 7 8 9]

array([6, 7, 8, 9])

Key patterns:

Pattern	Meaning

a[i, j]--	Single element

a[i, :]--	Row i

a[:, j]--	Column j

a[i:j, k:l]-- Sub-matrix slice

a[condition]--	Boolean/fancy indexing

a[[0,2]]--	Select specific rows by index list

Slices are views, not copies. modifying a slice modifies the original array. Use .copy() to avoid this.

**Assignment 3**

Given a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]):

Get the second row.

Get the last column.

Get all elements greater than 6.

Get the sub-array of the first two rows and last two columns.

In [23]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a[1, :]



array([5, 6, 7, 8])

In [24]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a[:, -1]

array([ 4,  8, 12])

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[a > 6]

array([ 7,  8,  9, 10, 11, 12])

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[0:2, 2:4]

array([[3, 4],
       [7, 8]])