**Array Operations & Broadcasting**

Concept: Operations apply element-wise by default, no loops needed.

 Broadcasting is NumPy's rule for handling operations between arrays of different shapes by "stretching" the smaller one, like automatically applying a single tax rate to every item in a cart without writing a loop.

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

a + b        #  element-wise




array([11, 22, 33])

In [5]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a * b            # element-wise multiply (not matrix mult)

array([10, 40, 90])

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a * 2

array([2, 4, 6])

In [7]:
m = np.array([[1,2,3],[4,5,6]])
m + a        # adds [1,2,3] to every row -> broadcasting

array([[2, 4, 6],
       [5, 7, 9]])

**Broadcasting rule** (compare shapes right to left):

dimensions are compatible if they are equal, or one of them is 1.

Key operations:

Operation	Example

'+' '-' '*' '/'	(Element-wise arithmetic)

**	 (Element-wise power)

np.sqrt(a)	(Element-wise square root)

np.exp(a)	(Element-wise exponential)

a @ b or np.dot(a,b)	(Matrix/dot product (NOT *))

**Exercise**

1. Given a = np.array([1,2,3]), compute a squared, element-wise.

2. Add a 1D array [100, 200, 300] to every row of a 3x3 matrix of ones.

3. Compute the dot product of [1,2,3] and [4,5,6].

In [8]:
#1
a = np.array([1,2,3])
a ** 2

array([1, 4, 9])

In [9]:
#2
np.ones((3,3)) + np.array([100,200,300])

array([[101., 201., 301.],
       [101., 201., 301.],
       [101., 201., 301.]])

In [10]:
#3
np.dot([1,2,3], [4,5,6])

np.int64(32)

**Reshaping, Stacking, Splitting**

Concept: Same data, different "view" of its shape. Total element count must stay constant when reshaping.

In [11]:
a = np.arange(12)
a.reshape(3, 4)      # reshape into 3 rows, 4 cols
a.reshape(3, -1)     # -1 = "figure this dimension out automatically"

a.flatten()          # collapse to 1D (returns a copy)
a.T                  # transpose (swap axes)

np.vstack([a, a])    # stack arrays vertically
np.hstack([a, a])    # stack arrays horizontally
np.split(a, 3)       # split into 3 equal parts

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

Key operations:

Operation	Purpose

.reshape(shape)	Change shape without changing data

.flatten() / .ravel()	Flatten to 1D

.T	Transpose

np.vstack, np.hstack	Stack arrays vertically/horizontally

np.concatenate([a,b], axis=)	Join arrays along an axis

np.split(a, n)	Split into n equal parts

**Exercise**

1. Create np.arange(16) and reshape it into a 4x4 matrix.

2. Transpose that matrix.

3. Stack two 1D arrays [1,2,3] and [4,5,6] vertically, then horizontally.

In [12]:
# 1
a = np.arange(16).reshape(4, 4)

In [13]:
# 2
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [15]:
# 3
np.vstack([[1,2,3],[4,5,6]])    # shape (2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.hstack([[1,2,3],[4,5,6]])    # shape (6,)  -> concatenated flat

array([1, 2, 3, 4, 5, 6])

**Aggregation & Statistics**

Concept: Functions that collapse an array into a summary value-- total, average, extremes: optionally along a specific axis (row-wise or column-wise) instead of the whole array.

In [18]:
a = np.array([[1,2,3],[4,5,6]])


In [19]:
a.sum()         #  sum of all elements


np.int64(21)

In [20]:
a.sum(axis=0)   #  sum down each column


array([5, 7, 9])

In [21]:
a.sum(axis=1)   # sum across each row


array([ 6, 15])

In [24]:
a.mean()        # average

np.float64(3.5)

In [25]:
a.std()         # standard deviation


np.float64(1.707825127659933)

In [26]:
a.min(), a.max()

(np.int64(1), np.int64(6))

In [27]:
a.argmax()      # index of the max value (flattened)

np.int64(5)

**Axis rule of thumb**:

 axis=0 collapses rows (result has one value per column).

 axis=1 collapses columns (one value per row).

Key operations:

Function	Purpose:

.sum(), .mean(), .std(), .var()

Basic statistics:

.min(), .max()

Extremes:

.argmin(), .argmax()

Index of extremes:

np.median(a)

Median:

.cumsum()

Running cumulative sum

**Exercise**

Given a = np.array([[4,1,7],[2,9,3]]):

1. Find the sum of each column.

2. Find the mean of each row.

3. Find the index of the maximum value in the flattened array.

In [28]:
a = np.array([[4,1,7],[2,9,3]])

In [29]:
# 1
a.sum(axis=0)

array([ 6, 10, 10])

In [30]:
# 2
a.mean(axis=1)

array([4.        , 4.66666667])

In [31]:
# 3
a.argmax()

np.int64(4)