In [3]:
## Numpy day1

In [4]:
pip install numpy

In [5]:
import numpy as np

In [10]:
a = np.array([10, 20, 30, 40, 50])

print(a)

[10 20 30 40 50]


In [6]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [7]:
##basic python list
numbers = [10, 20, 30, 40, 50]

In [8]:
## numpy list
numbers = np.array([10, 20, 30, 40, 50])

NumPy is particularly useful because it allows efficient vectorized numerical operations.

In [9]:
## for example
numbers = np.array([10, 20, 30, 40, 50])

print(numbers * 2)

[ 20  40  60  80 100]


In [ ]:
## with normal python code
numbers = [10, 20, 30]

print(numbers * 2)

In [11]:
# 2d array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
print(a.ndim)   ##checks the dimensions of the array

2


In [13]:
## for rows and colums. value of x defines no. of rows and y defines columns
print(a.shape)

(2, 3)


In [15]:
## total no. of elements
print(a.size)

6


In [16]:
## for datatypes
print(a.dtype)

int64


In [17]:
a = np.array([10, 20, 30, 40])

print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)

Dimensions: 1
Shape: (4,)
Size: 4
Data Type: int64


In [18]:
## special arrays
a = np.zeros(5)    # creates array of 5 0s

print(a)

[0. 0. 0. 0. 0.]


In [20]:
# 0 array for 2D
a = np.zeros((2, 3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# 1s array
a = np.ones(5)

print(a)

[1. 1. 1. 1. 1.]


In [23]:
# for 2D of 1s array
a = np.ones((2,3))

print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# 3D array of ones
a = np.ones((2, 3, 4)) # 2 layers, 3 rows, 4 columns

print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [26]:
## full array (creates array full of 10s 5times)
a = np.full(5, 10)

print(a)

[10 10 10 10 10]
