**Linear Algebra Essentials**

Concept: NumPy's linalg module covers the matrix math behind ML and data science: determinants, inverses, eigenvalues.

In [2]:
import numpy as np

In [3]:
m = np.array([[1,2],[3,4]])

In [4]:
np.linalg.det(m)         # determinant

np.float64(-2.0000000000000004)

In [5]:
np.linalg.inv(m)         # inverse matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
np.linalg.eig(m)         # eigenvalues, eigenvectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [7]:
np.linalg.solve(m, [1,2])  # solve system m @ x = [1,2]

array([0. , 0.5])

**The idea:**

m @ x = b is matrix notation for a system of equations. np.linalg.solve(m, b) finds the vector x that makes this true, without you manually doing elimination.

Concretely, for m = [[1,2],[3,4]] and b = [1,2]:

m @ x = b unpacks into two equations (where x = [x0, x1]):

1* x0 + 2* x1 = 1

3* x0 + 4* x1 = 2

np.linalg.solve(m, [1,2]) solves both equations at once and returns x0, x1.

example:

m = np.array([[1,2],[3,4]])

b = np.array([1,2])

x = np.linalg.solve(m, b)

print(x)        --[0.  0.5]

# verify: m @ x should equal b
print(m @ x)      -- [1. 2.]  

**Exercise**

1. Compute the determinant of [[2,0],[0,3]].

2. Compute the inverse of [[1,2],[3,4]].

3. Solve x + y = 5 and 2x + y = 8 using np.linalg.solve.

In [8]:
# 1
np.linalg.det(np.array([[2,0],[0,3]]))

np.float64(6.0)

In [10]:
# 2
np.linalg.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
# 3
A = np.array([[1,1],[2,1]])
b = np.array([5,8])
np.linalg.solve(A, b)

array([3., 2.])

**Random Module**

Concept: Used constantly for simulations, sampling, and shuffling data. Set a seed for reproducibility: same seed always gives the same "random" output.

In [12]:
np.random.seed(42)          # reproducibility


In [14]:
np.random.rand(3)           # 3 uniform floats [0,1)

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01])

In [15]:
np.random.randn(3)          # 3 samples from standard normal distribution


array([ 1.01051528,  0.02222183, -0.42779291])

In [16]:
np.random.randint(1, 100, 5)  # 5 random ints


array([42, 92, 60, 80, 15])

In [17]:
np.random.choice([1,2,3], size=2, replace=False)  # random sample, no repeats


array([1, 3])

In [19]:
np.random.shuffle(array)      # shuffle in place

NameError: name 'array' is not defined

**Exercise**

1. Set a seed, then generate 5 random integers between 1 and 100.

2. Simulate flipping a coin 10 times using np.random.choice(['H','T'], size=10).

3. Shuffle the array np.arange(10) in place.

In [20]:
#1
np.random.seed(1)
np.random.randint(1, 100, 5)

array([38, 13, 73, 10, 76])

In [21]:
# 2
np.random.choice(['H','T'], size=10)

array(['T', 'T', 'H', 'H', 'T', 'H', 'T', 'T', 'H', 'H'], dtype='<U1')

In [22]:
# 3
a = np.arange(10)
np.random.shuffle(a)

**File I/O**

Concept: Save/load arrays to disk without converting to Python lists first.

In [23]:
a = np.array([1,2,3])



In [24]:
np.save('arr.npy', a)          # save single array (binary)


In [25]:
b = np.load('arr.npy')         # load it back



In [27]:
np.savetxt('arr.csv', a, delimiter=',')   # save as text/CSV
c = np.loadtxt('arr.csv', delimiter=',')  # load from CSV

**Exercise**

1. Save a 3x3 array to a .npy file and load it back.
2. Save the same array as a .csv file using np.savetxt.

In [28]:
a = np.arange(9).reshape(3,3)

In [29]:
# 1
np.save('a.npy', a)
loaded = np.load('a.npy')

In [30]:
# 2
np.savetxt('a.csv', a, delimiter=',')